### ISSUE TITLE
Ongoing Minor Issue List (OCD List) SpongeDocs Edition

### ISSUE THREAD

**Issue by Tzky** [SpongePowered/SpongeDocs#437] opened 2016-01-16 21:42 UTC
I'd like to start an OCD post on the Docs repo, this way we don't push minor fixes but instead collect them and push them in bunches.

@SupaHam reported these two in '#sponge:
- [x] in `/plugin/debugging` phrasing in L91: 
  - [x] mention of Sponge(Vanilla) and missing SpongeForge
  - [x] "the sentences don't make any sense in this particular order" 
- [x] in `/plugin/event/causes`: `Optionml<Entity>` in L45

according to PR#447:
- [x] in `plugin/optional/usage.rst` (L166):  `if (optinalString.isPresent())`

I'll quote @phroa here:
- [x] the link to GenericArguments' source code on the argument parsing section is busted, should be https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/command/args/GenericArguments.java

@Dannyps reported:
- [x] in `server/getting-started/configuration/index` : `Saving a world config may be desired *after making modifications to the file*.` is confusing. It should read: `
  Saving a world config to the file may be desired after making modifications.`

**Comment by Deamon5550** [comment] 2016-01-17 00:24
in `/plugin/wgen/modifiers` the example for registering the world generator modifer needs to be updated to `Sponge.getRegistry().register(WorldGeneratorModifier.class, new MyModifier());`

**Comment by Tzky** [comment] 2016-02-05 21:03
I'll quote @phroa here:
- [ ] the link to GenericArguments' source code on the argument parsing section is busted, should be https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/command/args/GenericArguments.java

**Comment by Tzky** [comment] 2016-02-08 23:59
according to PR#447:

- [ ] in ``plugin/optional/usage.rst ( L#166):
   ``if (optinalString.isPresent()) {``

**Comment by Tzky** [comment] 2016-02-09 16:41
@Dannyps reported:
- [ ] in ``server/getting-started/configuration/index`` : ``Saving a world config may be desired *after making modifications to the file*.`` is confusing. It should read: ``
Saving a world config to the file may be desired after making modifications.``

**Comment by 12AwsomeMan34** [comment] 2016-02-11 23:24
- [ ] The page [about/introduction](https://docs.spongepowered.org/en/about/introduction.html) mentions that the project leaders are blood, sk89q, and Zidane. This should be updated in accordance with [about/staff](https://docs.spongepowered.org/en/about/staff.html).

**Comment by RedNesto** [comment] 2016-02-20 15:50
There is "how to" written twice in the latest Docs update: https://github.com/SpongePowered/SpongeDocs/commit/a33b9822618025446c255337841ebd271e046a8d#diff-1b21b02d7e6287095c0a769eab09ebc1R124

**Comment by Tzky** [comment] 2016-02-25 22:11
- [ ] the ``.. note::`` block on the ``downloads`` page needs rephrasing/clarification, as it stands it doesn't make any sense.

**Comment by 12AwsomeMan34** [comment] 2016-02-25 22:32
- [ ] In [registering the command on the CommandCallable page](https://docs.spongepowered.org/en/plugin/commands/commandcallable.html#registering-the-command), the example should be updated:
`new MyBroadcastCommand(server)` -> `new MyBroadcastCommand()`

**Comment by sanman00** [comment] 2017-01-07 18:47
At [plugin/injection](https://docs.spongepowered.org/master/en/plugin/injection.html), there is some text that reads `It’s entirely possible to receive the Game object from within most events [...]` which should probably read `It’s entirely possible to receive the Game object from Sponge.getGame()`.

Also in that file, towards the bottom, there is some text that reads `[...], where @ConfigDir refers to a directory`. I think the `where` should be a `while`.

**Comment by Inscrutable** [comment] 2017-01-08 04:36
I think it was meant to read ``whereas`` instead of ``where``. I can't speak for the other issue though.

**Comment by Minecrell** [comment] 2017-03-06 13:28
- [ ] [posting.rst](https://github.com/SpongePowered/SpongeDocs/blob/stable/source/about/posting.rst#categorizing-your-posts) under `Categorizing Your Posts`: `it's category` -> `its category`. [Reported on Crowdin](https://crowdin.com/translate/sponge-docs/802/en-nl#17670) by tomudding

**Comment by Inscrutable** [comment] 2017-04-02 07:40
A couple of issues raised by translators:  
- [ ] at /contributing/implementation/datamanipulator: ..."you want to have two constructors:" should be "you need to have two constructors:". (_want to_ is poor wording does not translate well)
- [ ] at /server/getting-started/configuration/server-properties: "white list" should be "whitelist" for consistency.

**Comment by randombyte-developer** [comment] 2017-04-09 14:19
The [permissions docs](https://docs.spongepowered.org/stable/en/plugin/permissions.html#permission) suggest using the plugin id as the 'root permisison node'. The example is `myPlugin`.
The [plugin id docs](https://docs.spongepowered.org/stable/en/plugin/plugin-identifier.html) say that plugin ids must be lowercase. And the example from the permission `myPlugin` isn't lowercase.

**Comment by connorhartley** [comment] 2017-04-10 06:23
https://docs.spongepowered.org/stable/en/plugin/injection.html#temporary-list-of-injected-types ConfigDir example should point to the `./configs/` directory instead of `./mods/`.

**Comment by Inscrutable** [comment] 2017-05-10 03:08
A new one found by tomudding: "sections" should not be a plural in the first line of https://docs.spongepowered.org/stable/en/contributing/index.html

**Comment by Inscrutable** [comment] 2017-05-25 10:28
https://docs.spongepowered.org/stable/en/about/faq.html#i-m-a-bukkit-plugin-developer-why-can-t-sponge-use-bukkit-s-api says "demise in September". This should have the year (2014). c/o - kashike

**Comment by Faegy** [comment] 2017-06-01 06:35
- [ ] https://docs.spongepowered.org/stable/en/plugin/event/causes.html misses "be" in "This contextual information can then used to modify the behavior of your event listener".

**Comment by Minecrell** [comment] 2017-06-12 11:03
- [ ] https://github.com/SpongePowered/SpongeDocs/issues/604

**Comment by randombyte-developer** [comment] 2017-06-18 17:11
https://docs.spongepowered.org/stable/en/plugin/scheduler.html#task-properties

For the task name:

```
... could look like “FooPlugin-A-12”. No two active tasks ...
```

The plugin id should be `foo-plugin`.

**Comment by Inscrutable** [comment] 2017-07-23 04:44
OK, Everything here has been fixed up to this point in PR #616 - let me know if anything's awry.

**Comment by Dannyps** [comment] 2017-08-25 16:30
https://github.com/SpongePowered/SpongeDocs/blob/stable/source/ore/routes/list-users.rst

*Limits the amount of **projects** returned (max / default: 25).*
should be
*Limits the amount of **users** returned (max / default: 25).*


*Drops the first *n* **projects** from the result list.*
should be
*Drops the first *n* **users** from the result list.*

**Comment by tomudding** [comment] 2017-09-12 16:09
**SpongeAPI** is sometimes incorrectly written as '**Sponge API**' (with a space). This list lists (hopefully) all of the occurrences of this "problem". I cannot provide a line-specific link here so someone will have to search for the instances and replace them by hand (or by using a text editor).

---
These files contain 1 or more occurrences of '**Sponge API**':
- [ ] [../source/about/faq.rst](https://raw.githubusercontent.com/SpongePowered/SpongeDocs/stable/source/about/faq.rst) - (4x) - 
- [ ] [../source/about/future.rst](https://raw.githubusercontent.com/SpongePowered/SpongeDocs/stable/source/about/future.rst) - (1x) - '_(...) building the **Sponge API** on top (...)_'
- [ ] [../source/about/glossary.rst](https://raw.githubusercontent.com/SpongePowered/SpongeDocs/stable/source/about/glossary.rst) - (1x) - under 'SpongeVanilla' -> '_(...) implementation of **Sponge API** that runs (...)_'
- [ ] [../source/about/introduction.rst](https://raw.githubusercontent.com/SpongePowered/SpongeDocs/stable/source/about/introduction.rst) - (5x) -
- [ ] [../source/about/license.rst](https://raw.githubusercontent.com/SpongePowered/SpongeDocs/stable/source/about/license.rst) - (1x) - '_(...) and the **Sponge API** are licensed (...)_'
- [ ] [../source/contributing/index.rst](https://raw.githubusercontent.com/SpongePowered/SpongeDocs/stable/source/contributing/index.rst) - (2x) - inside a link (under 'Intermediate Contributions' and 'Advanced Contributions').
- [ ] [../source/contributing/porting.rst](https://raw.githubusercontent.com/SpongePowered/SpongeDocs/stable/source/contributing/porting.rst) - (1x) - '_(...) implement the **Sponge API** on another (...)_'
- [ ] [../source/ore/guidelines.rst](https://raw.githubusercontent.com/SpongePowered/SpongeDocs/stable/source/ore/guidelines.rst) - (1x) - '_(...) use the **Sponge API** where possible. (...)_'
- [ ] [../source/ore/publish.rst](https://raw.githubusercontent.com/SpongePowered/SpongeDocs/stable/source/ore/publish.rst) - (1x) - '_(...) JAR. Luckily, **Sponge API** has a (...)_'
- [ ] [../source/plugin/bans.rst](https://raw.githubusercontent.com/SpongePowered/SpongeDocs/stable/source/plugin/bans.rst) - (1x) - under 'Getting the BanService' -> '_(...) in the **Sponge API**:  (...)_'
- [ ] [../source/plugin/index.rst](https://raw.githubusercontent.com/SpongePowered/SpongeDocs/stable/source/plugin/index.rst) - (3x) - all in the first paragraph
- [ ] [../source/plugin/plugin-class.rst](https://raw.githubusercontent.com/SpongePowered/SpongeDocs/stable/source/plugin/plugin-class.rst) - (2x) -
- [ ] [../source/plugin/practices.rst](https://raw.githubusercontent.com/SpongePowered/SpongeDocs/stable/source/plugin/practices.rst) - (7x) - 
- [ ] [../source/plugin/services.rst](https://raw.githubusercontent.com/SpongePowered/SpongeDocs/stable/source/plugin/services.rst) - (1x) - under 'Providing your own service' -> '_(...) of the **Sponge API** (e.g. economy, (...)_'
- [ ] [../source/plugin/configuration/index.rst](https://raw.githubusercontent.com/SpongePowered/SpongeDocs/stable/source/plugin/configuration/index.rst) - (2x) - '_(...) using the **Sponge API** have the (...)_' and '_The **Sponge API** offers the (...)_'
- [ ] [../source/plugin/configuration/nodes.rst](https://raw.githubusercontent.com/SpongePowered/SpongeDocs/stable/source/plugin/configuration/nodes.rst) - (1x) - under 'Defaults' -> '_(...) Unlike the **Sponge API**, the Configurate (...)_'
- [ ] [../source/plugin/entities/index.rst](https://raw.githubusercontent.com/SpongePowered/SpongeDocs/stable/source/plugin/entities/index.rst) - (1x) - '_(...) and the **Sponge API** in general._'
- [ ] [../source/plugin/optional/basic.rst](https://raw.githubusercontent.com/SpongePowered/SpongeDocs/stable/source/plugin/optional/basic.rst) - (2x) - '_(...) of the **Sponge API** makes use (...)_' (first paragraph) and '_(...) throughout the **Sponge API**._' (second paragraph)
- [ ] [../source/plugin/project/maven.rst](https://raw.githubusercontent.com/SpongePowered/SpongeDocs/stable/source/plugin/project/maven.rst) - (1x) - under 'Using the Plugin Archetype' -> '_(...) fact that **Sponge API** is not (...)_'
- [ ] [../source/plugin/text/messagechannels.rst](https://raw.githubusercontent.com/SpongePowered/SpongeDocs/stable/source/plugin/text/messagechannels.rst) - (1x) - '_(...) in the Sponge API as
``AbstractMutableMessageChannel``.(...)_'
- [ ] [../source/preparing/git.rst](https://raw.githubusercontent.com/SpongePowered/SpongeDocs/stable/source/preparing/git.rst) - (1x) - '_(...) and the **Sponge API**._'
- [ ] [../source/preparing/index.rst](https://raw.githubusercontent.com/SpongePowered/SpongeDocs/stable/source/preparing/index.rst) - (1x) - '_(...) with the **Sponge API** and for (...)_'
- [ ] [../source/server/index.rst](https://raw.githubusercontent.com/SpongePowered/SpongeDocs/stable/source/server/index.rst) - (2x) - 
- [ ] [../source/server/getting-started/configuration/hocon.rst](https://raw.githubusercontent.com/SpongePowered/SpongeDocs/stable/source/server/getting-started/configuration/hocon.rst) - (2x) - 
- [ ] [../source/server/getting-started/implementations/index.rst](https://raw.githubusercontent.com/SpongePowered/SpongeDocs/stable/source/server/getting-started/implementations/index.rst) - (1x) - '_The **Sponge API** itself is (...)_'
- [ ] [../source/server/getting-started/implementations/spongevanilla.rst](https://raw.githubusercontent.com/SpongePowered/SpongeDocs/stable/source/server/getting-started/implementations/spongevanilla.rst) - (2x) - 
- [ ] [../source/server/management/plugins.rst](https://raw.githubusercontent.com/SpongePowered/SpongeDocs/stable/source/server/management/plugins.rst) - (1x) - '_(...) bypass the **Sponge API**, or otherwise (...)_'
- [ ] [../source/server/spongineer/commands.rst](https://raw.githubusercontent.com/SpongePowered/SpongeDocs/stable/source/server/spongineer/commands.rst) - (1x) - under 'Forge' -> '_(...) of the **Sponge API**, such as (...)_'
- [ ] [../source/server/spongineer/debugging.rst](https://raw.githubusercontent.com/SpongePowered/SpongeDocs/stable/source/server/spongineer/debugging.rst) - (1x) - under '4. Is every (...)' -> '_The **Sponge API** is subject  (...)_'

---

_Please note that I have searched for these occurrences by hand, so it is possible that I missed a few of them._ 

Afterthought: I should have written a program for this 😞, maybe next time, when I'll iterate over the 'Sponge Forge'/'Sponge Vanilla' problem.

**Comment by ryantheleach** [comment] 2017-09-13 01:31
I haven't investigated, but there is a grammatical difference between talking about the artifact SpongeAPI and more weakly referencing it as the Sponge API.

If you are referencing the (sub)projects name it's SpongeAPI if you are referring to it as the API alongside the Sponge implementations, it would be "the Sponge API"

Long story short, if you can drop in replace the word 'API' into 'Sponge API' it's a good fit for using 'Sponge API' as it's explicitly talking about *which* API (ours) if you can not, you are probably referring to the artifact itself, 'SpongeAPI'

**Comment by ST-DDT** [comment] 2017-09-13 19:02
https://github.com/SpongePowered/SpongeDocs/blame/stable/source/plugin/blocks/accessing.rst#L108
https://github.com/SpongePowered/SpongeDocs/blame/master/source/plugin/blocks/accessing.rst#L108

> It stores all immutable value's for a particular block.

`value's` -> `values`

**Comment by tomudding** [comment] 2017-09-13 19:14
@ryantheleach That is indeed an interesting thing I didn't think of. I was just thinking to change it so everything is the same throughout the Docs (as once mentioned in #docs on Discord), not keeping something like this in mind.

In most cases it probably won't matter which one you'll use, because it will still be obvious what we mean.

I'll leave this decision (and the grammatical aspects of it) to the person who is going to "clean it up" 😉

**Comment by tomudding** [comment] 2017-09-13 19:22
To keep the usage of certain terms consistent throughout a file/the whole docs a few things need to change (this list will be updated in the future):

- [ ] Change '_int_' in [[../source/server/getting-started/configuration/sponge-conf.rst](https://raw.githubusercontent.com/SpongePowered/SpongeDocs/stable/source/server/getting-started/configuration/sponge-conf.rst)] (under 'Spawner') to '_integer_' (as integer is used throughout the whole file)

**Comment by ST-DDT** [comment] 2017-09-13 20:22
https://github.com/SpongePowered/SpongeDocs/blame/stable/source/plugin/blocks/concepts.rst#L41

> This is illustrated below::

Remove double `:`

**Comment by ST-DDT** [comment] 2017-09-16 09:25
https://github.com/SpongePowered/SpongeDocs/blame/stable/source/plugin/commands/flags.rst#L101-L102

> Using a long flag, you can specify a value along with the flag using equals in the command.

This sentence is hard to understand. maybe it should be changed to:

`using the equal character (``=``) in the command`
or 
`using equals (``=``) in the command`

**Comment by ST-DDT** [comment] 2017-09-21 18:04
https://github.com/SpongePowered/SpongeDocs/blame/stable/source/plugin/entities/spawning.rst#L16

> You will need four things for spawning in an Entity, a Location, an Extent, and an EntityType.

This should probably be: 

`You will need three things for spawning an Entity: a Location, an Extent, and an EntityType.`

**Comment by ST-DDT** [comment] 2017-09-23 17:59
https://github.com/SpongePowered/SpongeDocs/blame/stable/source/plugin/items/usage.rst#L79-L80

> We can check if a block can mine obsidian by using the :javadoc:`HarvestingProperty` of that item.

`block` -> `tool` or `item`

**Comment by ST-DDT** [comment] 2017-09-24 10:05
https://github.com/SpongePowered/SpongeDocs/blame/stable/source/plugin/optional/basic.rst#L84

> The API authors can define an implicit nullable contract on every API method, in an attempt to make null handling the plugin author's problem, which only exacerbates the previous problem.

This sentence is really unclear IMO. It would be clearer if it would be changed to
`... exacerbates the previous solution.`

**Comment by ST-DDT** [comment] 2017-09-27 19:06
* [x] https://github.com/SpongePowered/SpongeDocs/blob/stable/source/plugin/text/representations/xml.rst
https://docs.spongepowered.org/stable/de/plugin/text/representations/xml.html

> TextXML Format

This section is obsolete/deprecated, because it does no longer exist in the [API](https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/text/serializer/TextSerializers.java) AFAICT.

**Comment by ST-DDT** [comment] 2017-09-30 12:59
https://github.com/SpongePowered/SpongeDocs/blame/stable/source/plugin/text/representations/configurate.rst#L19-L20

> For example, the text “Hello World!”, formatted with the color red and and underline would have the following HOCON representation:

The second `and` should be an `an`.

**Comment by ST-DDT** [comment] 2017-09-30 13:03
https://github.com/SpongePowered/SpongeDocs/blame/stable/source/plugin/text/index.rst#L9-L10

> Formatted Text can be created using the Text.Builder, as described in this section. The robust Text API can be used in a variety of ways to combine styling, coloring, and [Text](https://jd.spongepowered.org/6.0.0/org/spongepowered/api/text/Text.html) actions.

The `Text` link at the end should be replaced by a link to `TextAction`.

**Comment by Dannyps** [comment] 2017-10-12 21:20
I'll take care of the issues after the SpongeAPI/Sponge API discussion. You may let your OCD drop just a bit for the next few days :)

**Comment by ST-DDT** [comment] 2017-10-14 12:47
https://github.com/SpongePowered/SpongeDocs/blame/stable/source/plugin/effects.rst#L35-L36

> First, we have the `SoundType` **being played**. This is simply the sound that will **be played**.

This sentence looks douplicated IMO.

**Comment by ST-DDT** [comment] 2017-10-14 21:02
https://github.com/SpongePowered/SpongeDocs/blame/stable/source/plugin/effects.rst#L88

> Similarly to **potions and sounds**, we need to use a builder to create our potion effect:

Should probably be `particles and sounds` (because that are the previous examples).

**Comment by ST-DDT** [comment] 2017-10-14 21:11
https://github.com/SpongePowered/SpongeDocs/blame/stable/source/plugin/effects.rst#L85

> Creating Potions

I'm not sure whether this is the right header/title. As the section is actually about `PotionEffects`.
(Nothing to drink or throw at all.)
I know that is a subsection of `effects` but both terms exist and there is an important difference between both.

**Comment by ImMorpheus** [comment] 2017-10-23 13:08
- [ ] https://github.com/SpongePowered/SpongeDocs/blame/stable/source/about/glossary.rst#L22 | http://www.minecraftforge.net/wiki/Core_Mod is dead. 

- [ ] https://github.com/SpongePowered/SpongeDocs/blame/stable/source/about/glossary.rst#L32  | http://www.minecraftforge.net/wiki/ -> https://mcforge.readthedocs.io/en/latest/ 

- [ ] https://github.com/SpongePowered/SpongeDocs/blame/stable/source/about/history.rst#L63 | http://dragonspainter.deviantart.com/ -> https://dragonspainter.deviantart.com/

- [ ] https://github.com/SpongePowered/SpongeDocs/blame/stable/source/conf.py#L94 | http://zml2008.github.io/configurate/apidocs/ -> http://configurate.aoeu.xyz/apidocs/

- [ ] https://github.com/SpongePowered/SpongeDocs/blame/stable/source/plugin/blocks/concepts.rst#L60 | http://minecraft.gamepedia.com/NBT_format -> https://minecraft.gamepedia.com/NBT_format

- [ ] https://github.com/SpongePowered/SpongeDocs/blame/stable/source/plugin/text/representations/formatting-code-legacy.rst#L15 | http://minecraft.gamepedia.com/Formatting_codes -> https://minecraft.gamepedia.com/Formatting_codes

- [ ] https://github.com/SpongePowered/SpongeDocs/blame/stable/source/plugin/text/representations/json.rst#L7 | http://minecraft.gamepedia.com/Commands#Raw_JSON_Text -> https://minecraft.gamepedia.com/Commands#Raw_JSON_Text

- [ ] https://github.com/SpongePowered/SpongeDocs/blame/stable/source/plugin/text/text.rst#L142 | http://minecraft.gamepedia.com/Commands#Target_selectors -> https://minecraft.gamepedia.com/Commands#Target_selectors

- [ ] https://github.com/SpongePowered/SpongeDocs/blame/stable/source/server/getting-started/configuration/server-properties.rst#L57 | http://minecraft.gamepedia.com -> https://minecraft.gamepedia.com/Minecraft_Wiki

- [ ] https://github.com/SpongePowered/SpongeDocs/blame/stable/source/server/getting-started/configuration/server-properties.rst#L137 | http://minecraft.gamepedia.com/Superflat -> https://minecraft.gamepedia.com/Superflat

- [ ] https://github.com/SpongePowered/SpongeDocs/blame/stable/source/server/getting-started/configuration/server-properties.rst#L139 | http://minecraft.gamepedia.com/Customized -> https://minecraft.gamepedia.com/Customized

- [ ] https://github.com/SpongePowered/SpongeDocs/blame/stable/source/server/getting-started/implementations/spongeforge.rst#L5 | http://www.minecraftforge.net/ -> http://www.minecraftforge.net/forum/ 

- [ ] https://github.com/SpongePowered/SpongeDocs/blame/stable/source/server/getting-started/implementations/spongeforge.rst#L71 | http://files.minecraftforge.net/ -> https://files.minecraftforge.net/

- [ ] https://github.com/SpongePowered/SpongeDocs/blame/stable/source/server/management/bans.rst#L19 | http://minecraft.gamepedia.com/Commands#ban -> https://minecraft.gamepedia.com/Commands#ban

- [ ] https://github.com/SpongePowered/SpongeDocs/blame/stable/source/server/management/permissions.rst#L14 | http://minecraft.gamepedia.com/Op -> https://minecraft.gamepedia.com/Op

- [ ] https://github.com/SpongePowered/SpongeDocs/blame/stable/source/server/management/permissions.rst#L21 | http://minecraft.gamepedia.com/Commands#Summary_of_commands -> https://minecraft.gamepedia.com/Commands#Summary_of_commands

- [ ] https://github.com/SpongePowered/SpongeDocs/blame/stable/source/server/spongineer/bugreport.rst#L18 | http://pastebin.com/ -> https://pastebin.com/

- [ ] https://github.com/SpongePowered/SpongeDocs/blame/stable/source/server/spongineer/commands.rst#L201 | http://minecraft.gamepedia.com/Commands#List_of_commands -> https://minecraft.gamepedia.com/Commands#List_of_commands

**Comment by ryantheleach** [comment] 2017-10-24 00:02
Offtopic: I'm not sure of the reasons of Forge moving to ReadTheDocs I just remember that we migrated away, hope it's not a issue they will run into.

**Comment by ST-DDT** [comment] 2017-11-19 19:58
https://github.com/SpongePowered/SpongeDocs/blame/stable/source/contributing/spongedocs.rst#L35

Code Styling/formatting

and also

> Contributions implicitly accept this licensing.

`Contributions` or `Contributors`?

**Comment by InterStena** [comment] 2017-11-27 15:13
https://github.com/SpongePowered/SpongeDocs/blame/stable/source/server/spongineer/logs.rst#L5

> This pages contains

Should be:

> This page contains

**Comment by ST-DDT** [comment] 2017-12-10 11:14
* [x] https://github.com/SpongePowered/SpongeDocs/blame/stable/source/server/getting-started/configuration/sponge-conf.rst#L113

> Set to false if you want mod to ignore entity collision rules.

Should be

`Set to false if you want this mod to ignore entity collision rules.`
This is also wrong in the default config.

**Comment by phit** [comment] 2017-12-10 11:23
the config files in general really need some cleanup, lots of outdated comments

**Comment by ryantheleach** [comment] 2018-01-08 15:28
https://docs.spongepowered.org/stable/en/server/spongineer/commands.html Should mention the /minecraft:xyz fallbacks in an info box.

**Comment by MinusKube** [comment] 2018-01-30 22:02
The text `Examples of block properties` in `plugin/blocks/concepts` is not translatable.
I guess it's due to the `topic`.

https://github.com/SpongePowered/SpongeDocs/blame/stable/source/plugin/blocks/concepts.rst#L13

**Comment by Inscrutable** [comment] 2018-01-31 09:03
Regarding the ``plugin/blocks/concepts`` page issue: As we rarely used ``topic`` anywhere in the docs, we can reformat that bit and see what happens. It *should* be editable, just like the contents of a ``note`` or a ``tip``, but we have noticed some eccentricities in the translatable parts on Crowdin recently.

**Comment by Dannyps** [comment] 2018-02-12 23:37
- [ ] https://github.com/SpongePowered/SpongeDocs/blame/stable/source/ore/publish.rst#L96
`If you're using build manager` should be `If you're using **a** build manager`. I think.

**Comment by Inscrutable** [comment] 2018-02-14 15:13
- [x] On the ``server/getting-started`` page, SpongeForge needs at least Java 8 build _20_, not _40_.

**Comment by ST-DDT** [comment] 2018-02-26 18:31
* [ ] https://github.com/SpongePowered/SpongeDocs/blame/stable/source/plugin/economy/practices.rst#L64

Is:

> `if (result.getResult() == ResultType.SUCCESS)) {`

Should be:

> `if (result.getResult() == ResultType.SUCCESS) {`

(Remove duplicate bracket)

As reported by #668 .

**Comment by ST-DDT** [comment] 2018-03-01 22:10
* [ ] https://github.com/SpongePowered/SpongeDocs/blame/stable/source/ore/publish.rst#L156

is:

> `If you hover choose to add it to another page the page will only show when the parent page is expanded.`


Mentioned by @Dannyps on IRC:

> Isn't the word hover an intruder, in that line?

**Comment by TheNullablePrototype** [comment] 2018-03-04 14:55
_An error in the documentation or something I do not understand?_
http://joxi.ru/MAjlOW5u4My50m
https://docs.spongepowered.org/stable/ru/plugin/offline-userplayer-data.html#code-example

**Comment by ST-DDT** [comment] 2018-03-04 18:55
@ImagePrototype Yes thats an error in the documentation:

Should probably be:
````java
if (onlinePlayer.isPresent()) {
	return onlinePlayer.map(v -> v);
}
````

Ref: https://github.com/SpongePowered/SpongeDocs/blame/stable/source/plugin/offline-userplayer-data.rst#L44

But this piece of code looks too confusing anyway. We should probably ask the API team for the recommended way to do it.

EDIT: According to killjoy checking the online players first is unnecessary overhead.

**Comment by Inscrutable** [comment] 2018-03-05 12:04
That one probably justifies a separate issue, if only so we can add a reviewer or two. It certainly seems to be larger than the usual trivial issues we put here.

**Comment by tomudding** [comment] 2018-03-30 08:00
A few Terms of Service related issues:

- [x] https://github.com/SpongePowered/SpongeDocs/blame/stable/source/about/tos.rst#L105
It should be `(3.4) Ore` because Ore should be outside the parentheses, like all other platforms mentioned.

- [x] https://github.com/SpongePowered/SpongeDocs/blame/stable/source/about/tos.rst#L33
Missing a `,` between `“Our” “SpongePowered”`.

**Comment by Grauldon** [comment] 2018-05-24 21:36
I have 7 more commits ready for another PR.  I am going through this list and checking for more changes I can make.  I hope to have a PR ready in the next day or two.

**Comment by Grauldon** [comment] 2018-05-25 02:56
***
I have commits ready for the following issues:

> ST-DDT's [comment](https://github.com/SpongePowered/SpongeDocs/issues/437#issuecomment-336632973) about sentence duplication on Oct 14, 2017

> MinusKube's [comment](https://github.com/SpongePowered/SpongeDocs/issues/437#issuecomment-361749474) about translating section title on Jan 30, 2018 and Inscrutable's [response](https://github.com/SpongePowered/SpongeDocs/issues/437#issuecomment-361867412) on Jan 31, 2018

> Dannyps' [comment](https://github.com/SpongePowered/SpongeDocs/issues/437#issuecomment-365100702) about a sentence missing "a" on Feb 12, 2018
	
> ST-DDT's [comment](https://github.com/SpongePowered/SpongeDocs/issues/437#issuecomment-368601329) about removing an extra ")" in example on Feb 26, 2018
						
> ST-DDT's [comment](https://github.com/SpongePowered/SpongeDocs/issues/437#issuecomment-369748605) about an extra word in sentence on Mar 1, 2018
	
> Inscrutable's [comment](https://github.com/SpongePowered/SpongeDocs/issues/437#issuecomment-365637562) about the minimum Java 8 build on Feb 14, 2018

> Dannyps' [comment](https://github.com/SpongePowered/SpongeDocs/issues/437#issuecomment-324971059) about the query parameters table on Aug 25, 2017
***
I can do the work for the following issues; I just need some guidance and/or decisions from someone more familiar with the documentation/code:

> ST-DDT's [comment](https://github.com/SpongePowered/SpongeDocs/issues/437#issuecomment-336667761) about section title on Oct 14, 2017

> Phit's [comment](https://github.com/SpongePowered/SpongeDocs/issues/437#issuecomment-350541365) about the config files need some cleanup on Dec 10, 2017

> ryantheleach's [comment](https://github.com/SpongePowered/SpongeDocs/issues/437#issuecomment-355997997) about mentioning the /minecraft:xyz fallbacks on Jan 8, 2018

> ST-DDT's [comment](https://github.com/SpongePowered/SpongeDocs/issues/437#issuecomment-345544749) about Code Style/formatting and correcting a sentence on Nov 19, 2017
***	
Once these issues are resolved, the only remaining issue after [PR #616](https://github.com/SpongePowered/SpongeDocs/issues/437#issuecomment-317228700) is the SpongeAPI vs Sponge API comments starting with [tomudding](https://github.com/SpongePowered/SpongeDocs/issues/437#issuecomment-328901973).
	
ImMorpheus' [comment](https://github.com/SpongePowered/SpongeDocs/issues/437#issuecomment-338653022) is complete AFAICT, but I have not checked the full list.

**Comment by ST-DDT** [comment] 2018-05-25 06:08
>    ST-DDT's comment about section title on Oct 14, 2017

Go for `PotionEffects`

>    Phit's comment about the config files need some cleanup on Dec 10, 2017

AFAICT this refers to the config files itself and not the documentation, so there is nothing for us to do here.

>    ryantheleach's comment about mentioning the /minecraft:xyz fallbacks on Jan 8, 2018

Just write a short paragraph mentioning this and we will comment on it in your PR.

>  ST-DDT's comment about Code Style/formatting and correcting a sentence on Nov 19, 2017

Add linebreaks and go for `Contributors`.

> Once these issues are resolved, the only remaining issue after PR #616 is the SpongeAPI vs Sponge API comments starting with tomudding.

IMO this can be ignored. If someone finds a wrong usage of this term he should report it here or fix it. Because otherwise we need a grammar master to identify them all. We should pay attention to that in new PRs though.

**Comment by ryantheleach** [comment] 2018-05-25 08:00
>ryantheleach's comment about mentioning the /minecraft:xyz fallbacks on Jan 8, 2018

in short, when there are conflicting commands in Sponge, that conflict with the games native commands, we also have the command's primary alias, with a prefix of the mod/game/plugin.

So if someone registers a /tp command in a plugin, that is say, incompatible with your camera mod, if you can configure your camera mod to use /minecraft:tp instead, you will get the expected behavior again.

The same goes with conflicting commands from multiple plugins. e.g. you could have /nucleus:tp and /easywarps:tp

It's a common question that appears on the forums occasionally.

**Comment by Grauldon** [comment] 2018-05-26 01:21
I have the changes ready.  I just need to sort out some issues with git / github.  I am still getting git's workflow down.

**Comment by ST-DDT** [comment] 2018-05-26 20:45
Once @Grauldon 's changes are included, I will update most code examples. 
The PR for that is almost ready just waiting for https://github.com/SpongePowered/SpongeAPI/issues/1839#issuecomment-392287826.

**Comment by ST-DDT** [comment] 2018-05-30 18:56
AFAICT we have now solved all issues listed here, so I guess we can close this issue (and create a new one for future comments). Objections?

**Comment by phit** [comment] 2018-05-30 18:58
we could also delete all comments that are no longer relevant, similar to other minor issue lists in the org

**Comment by Inscrutable** [comment] 2018-06-01 10:09
I would rather close this issue and keep the comments, and just make a Fresh issue. Should we continue calling it the 'OCD' List (which does have unwanted connotations), or something a little more sanitised?

**Comment by phit** [comment] 2018-06-01 15:18
I'd say drop the parentheses, and just call it "Ongoing Minor Issue List SpongeDocs Edition" and make a new issue

**Comment by Inscrutable** [comment] 2018-06-02 06:53
Closing this to make way for the new-born #698

**Closed by Inscrutable** 2018-06-02 06:53 UTC
Labels: input wanted
