### ISSUE TITLE
Dead link on "Custom Data" page

### ISSUE THREAD

**Issue by VapidLinus** [SpongePowered/SpongeDocs#590] opened 2017-04-02 09:10 UTC
On this page:
https://docs.spongepowered.org/stable/en/plugin/data/custom/index.html

The link that says "full implementation" seems to be dead. It links to:
https://github.com/SpongePowered/Cookbook/tree/master/Plugin/MyHomes

**Comment by ST-DDT** [comment] 2017-04-02 09:34
I guess the proper target would be [CustomData](https://github.com/SpongePowered/Cookbook/tree/custom-data/Plugin/CustomData) plugin (API 5) or [MyHomes](https://github.com/SpongePowered/Cookbook/pull/17) plugin (API 6).

Duplicate of: https://github.com/SpongePowered/SpongeDocs/issues/581

**Closed by ST-DDT** 2017-04-02 09:34 UTC
